### ISSUE TITLE
can we make PSSMGen more flexible

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/PSSMGen#1]
Situation 1: Most of the time, a user wants to calculate a pssm with a sequence as input. And use the calculated pssm for something that is totally not related with pdb. Therefore, assuming a user to have a pdb file is not very reasonable (i.e., initiate the object with a pdb is not very reasonable).

Situation 2: Many times I want to generate a pssm_raw file and map it to multiple pdb files. If I want to use PSSMGen, I will need to create a folder structure for each pdb file… This is not efficient… 

Can we make pssmgen more flexible by:

1. initiate the object with a fasta file instead of a pdb file
2. allow user to input pdb file to map_pssm, such as map_pssm(pdbFL). This way I can loop over this function alone.

**Comment by CunliangGeng** [comment]
The code is updated and check README for example cases.
