### ISSUE TITLE
'pdb2sql' object has no attribute 'close'

### ISSUE THREAD

**Issue by MohamedKhaled20-eng** [DeepRank/PSSMGen#12]
**Describe the bug**

**Environment:**
Jupyter Notebook
- OS system:
- win10
- Version:
- Branch commit ID: 
- Inputs:

**To Reproduce**
Steps/commands to reproduce the behavior:
 1.  I use Pssmgen to extract fasta from pdb 

**Expected Results**
fatsa files 
**Actual Results or Error Info**
'pdb2sql' object has no attribute 'close'

**Additional Context**
gen = PSSM('/pssmgen/1A2K')
gen.get_fasta(pdb_dir='/pssmgen/pdb', pdbref='C:\\Users\\fci_cu\\Downloads\\pssmgen\\pdb\\1A2K-l-u_A.pdb', chain=('A'), out_dir='C:\\Users\\fci_cu\\Downloads\\pssmgen\\fasta')

**Comment by CunliangGeng** [comment]
Thanks for reporting the issue. We have solved this issue before. Could you check the version of `pdb2sql` and `pssmgen` version you are using?

You could install the latest version with 
```
pip install pdb2sql==0.5.0
pip install PSSMGen==0.1.1
```

Let me know if you have further questions.

**Comment by MohamedKhaled20-eng** [comment]
I already use  pdb2sql==0.5.0 and  PSSMGen==0.1.1 but the issue is still 
but the fasta file generated 
![Screenshot ](https://user-images.githubusercontent.com/42678213/107076451-211a8780-67f4-11eb-888a-a4abe4d6dba9.png)

**Comment by CunliangGeng** [comment]
I just released a new version 0.1.2, try it please
`pip install PSSMGen==0.1.2`

**Comment by MohamedKhaled20-eng** [comment]
another problem appear after update the version 
PSSM module is  not defined 
![Screenshot2 ](https://user-images.githubusercontent.com/42678213/107113075-2106a000-6865-11eb-9f19-27f4ec105e14.png)

**Comment by CunliangGeng** [comment]
You need to import it before using, like: `from pssmgen import PSSM`.
