### ISSUE TITLE
Non-zero return code 1 from '"C:\\Program Files\\NCBI\\blast-2.11.0+\\bin\\psi" -out 

### ISSUE THREAD

**Issue by MohamedKhaled20-eng** [DeepRank/PSSMGen#13]
**Describe the bug**

**Environment:**
- OS system:
- Version:
- Branch commit ID: 
- Inputs:

**Expected Results**
generate PSSM 
**Actual Results or Error Info**
ApplicationError: Non-zero return code 1 from '"C:\\Program Files\\NCBI\\blast-2.11.0+\\bin\\psi" -out C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw\\1A2K-l-b.A.xml -outfmt "7 qseqid qgi qacc qaccver qlen sseqid sallseqid sgi sallgi   ,                   sacc saccver sallacc slen qstart qend sstart send qseq sseq  ,                   evalue bitscore score length pident nident mismatch positive ,                   gapopen gaps ppos frames qframe sframe btop staxids stitle   ,                   salltitles sstrand qcovs qcovhsp qcovus" -query C:\\Users\\fci_cu\\Downloads\\pssmgen\\fasta\\1A2K-l-b.A.fasta -db E:\\Graduation project\\nr.01 -evalue 0.0001 -word_size 2 -max_target_seqs 2000 -num_threads 4 -gapopen 9 -gapextend 1 -matrix PAM30 -comp_based_stats T -num_iterations 3 -out_pssm C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw\\1A2K-l-b.A.cptpssm -out_ascii_pssm C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw\\1A2K-l-b.A.pssm -save_pssm_after_last_round -save_each_pssm', message '\'"C:\\Program Files\\NCBI\\blast-2.11.0+\\bin\\psi"\' is not recognized as an internal or external command,'

​

**Additional Context**
from pssmgen import PSSM

gen = PSSM(work_dir='/pssmgen/1A2K')

gen.configure(blast_exe='C:\\Program Files\\NCBI\\blast-2.11.0+\\bin\psi',
            database='E:\\nr.01',
            num_threads = 4, evalue=0.0001, comp_based_stats='T',
            max_target_seqs=2000, num_iterations=3, outfmt=7,
            save_each_pssm=True, save_pssm_after_last_round=True)

gen.get_pssm(fasta_dir='C:\\Users\\fci_cu\\Downloads\\pssmgen\\fasta', out_dir='C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw', run=True, )

**Comment by CunliangGeng** [comment]
As you can see from the error `''"C:\Program Files\NCBI\blast-2.11.0+\bin\psi"' is not recognized as an internal or external command,'`, there is no `psi` command.

You need to use `psiblast`, i.e. `gen.configure(blast_exe='C:\Program Files\NCBI\blast-2.11.0+\bin\psiblast',...`
