### ISSUE TITLE
Error in pssm.py Non-zero return code 1 from '"NCBI\\blast-2.11.0+\\bin\\psiblast ( #run the blast query psi_cline())

### ISSUE THREAD

**Issue by MohamedKhaled20-eng** [DeepRank/PSSMGen#14]
**Describe the bug**

**Environment:**
- OS system: win10 
- Version: 1.1.0
- Branch commit ID: 
- Inputs:
- 
 

**Expected Results**
generate pssm 
**Actual Results or Error Info**
ApplicationError: Non-zero return code 1 from '"C:\\Program Files\\NCBI\\blast-2.11.0+\\bin\\psiblast" -out C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw\\1A2K-l-b.A.xml -outfmt "7 qseqid qgi qacc qaccver qlen sseqid sallseqid sgi sallgi   ,                   sacc saccver sallacc slen qstart qend sstart send qseq sseq  ,                   evalue bitscore score length pident nident mismatch positive ,                   gapopen gaps ppos frames qframe sframe btop staxids stitle   ,                   salltitles sstrand qcovs qcovhsp qcovus" -query C:\\Users\\fci_cu\\Downloads\\pssmgen\\fasta\\1A2K-l-b.A.fasta -db E:\\Graduation project\\nr.01 -evalue 0.0001 -word_size 2 -max_target_seqs 2000 -num_threads 4 -gapopen 9 -gapextend 1 -matrix PAM30 -comp_based_stats T -num_iterations 3 -out_pssm C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw\\1A2K-l-b.A.cptpssm -out_ascii_pssm C:\\Users\\fci_cu\\Downloads\\pssmgen\\pssm_raw\\1A2K-l-b.A.pssm -save_pssm_after_last_round -save_each_pssm', message 'USAGE'
**Additional Context**
![Screenshot ](https://user-images.githubusercontent.com/42678213/107076711-7b1b4d00-67f4-11eb-9964-ef78da362544.png)

**Comment by CunliangGeng** [comment]
It seems you're using a wrong `work_dir='/pssmgen/1A2K'`, are you sure you should use `/` but not `\\` on windows?

BTW, you could run the code in your `pssmgen` folder, then you just need to set `work_dir='1A2K`, and you can then leave the directory settings in `gen.get_pssm` as default.
