### ISSUE TITLE
Readme should specify that we use the nr blast database

### ISSUE THREAD

**Issue by FarzanehParizi** [DeepRank/PSSMGen#3]

**Comment by CunliangGeng** [comment]
I'd keep it open and leave it to users to choose which database to use based on their own needs.

**Comment by LilySnow** [comment]
Not all the databases can be used to generate pssms, for example, pdb. We should at least recommend the nr db. We should not add uncessary roadblocks for the users to use this software.

**Comment by CunliangGeng** [comment]
Added in README. Close this issue now.
