### ISSUE TITLE
REAMDE provides misleading examples

### ISSUE THREAD

**Issue by FarzanehParizi** [DeepRank/PSSMGen#4]
For example, in "Using customed PSSM files" section, the example uses `gen.map_pssm()`. This code (after checking the source code), in fact, by default assumes the chain ID is A and B, which most of the time is not the case. When the chain ID is not A and B, we run into error messages.

It will be clearer if we use the example as `gen.map_pssm(chain = ['C'])`.

**Comment by CunliangGeng** [comment]
Corrected in README. Close the issue now.
