### ISSUE TITLE
change of outfmt=7 to another readable format

### ISSUE THREAD

**Issue by FarzanehParizi** [DeepRank/PSSMGen#7]
The use of outfmt=7 into tabular format is not a good choice, as it is not easily readable. And its output format should be *.tbl not *.xml.

**Comment by CunliangGeng** [comment]
Actually I have tried all the other output formats before and tbl is the most convenient one to extract information. The output is huge and the proper way to look the output is to extract the info you need but not try to view everything (even other formats cannot give you a very clear view).

There is a bug in the code that make users cannot change the format, I'll fix it then you can set the format you like.

**Comment by CunliangGeng** [comment]
The bug is fixed in commit fe3f0369, and you can set your own format now.

**Comment by LilySnow** [comment]
We should do `pip install` again, right?

**Comment by CunliangGeng** [comment]
Yes, considering we are updating code, maybe it's better for you to download this repo  and install it with `cd PSSMgen; pip install -e ./` . Then later, you just need to pull the code to get updated.
